Mrna clean clustering
boulderrinnlab/CLASS_2020 pull request #45
Opened 2020-04-17 21:13 UTC by soraya-s

2020-04-20 18:37 UTC, msmallegan requested changes

2020-04-20 18:37 UTC, msmallegan commented on analysis/02_global_clustering/global_clustering.Rmd
Looks there's still a bit to clean up here, for ex. line 79 still has HINT. We'll wait to merge it until all this is cleaned up.

2020-04-27 15:17 UTC, shle4568 approved these changes
I made additional deletions to clean the code, am now confused on how to do a new pull request with the resulting code/how to resolve this from within the existing pull request. Hopefully this fixes things and doesn't mess anything up!

2020-04-27 17:55 UTC, boulderrinnlab commented on analysis/00_class_exercises/mrna_group/enriched_factors_on_reservoirs.Rmd
> +## How do we find expected number of ghosts??
I would take one more pass on markdown and clean up

2020-04-27 17:55 UTC, boulderrinnlab commented on analysis/00_class_exercises/mrna_group/enriched_factors_on_reservoirs.Rmd
> +## Are these reasonable break points? How would consider changing them?
Clean up markdown

2020-04-27 19:33 UTC, closed without merging